### ISSUE TITLE
[Bug] Settings dialog cannot be closed

### ISSUE THREAD

**Issue by Spyromaniac31** [FireCubeStudios/fluent-rooler-demo#1]
Clicking the 'X' on the Settings window does not do anything.

**Comment by FireCubeStudios** [comment]
Looking into this

**Comment by shafschwd** [comment]
can confirm same thing happened with me too 



https://user-images.githubusercontent.com/35454710/153081777-7a0fbfbe-9ea4-4013-a9fb-32cd2c3e95fb.mp4

**Comment by jaigak** [comment]
It looks like the original implementer forgot to implement this, I've fixed it and will open a pull request along with other improvements.
